// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCkgDVQk0GUQNC6Od_CNNx8Cj_M2xa9nCk',
    appId: '1:271731699482:web:b23381d27abd3322efc6a3',
    messagingSenderId: '271731699482',
    projectId: 'homeescape-75db4',
    authDomain: 'homeescape-75db4.firebaseapp.com',
    storageBucket: 'homeescape-75db4.appspot.com',
    measurementId: 'G-81RLXPEJTJ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDlnk1cxZNDZ1XzzY4SdfcLePKvQcFVFfw',
    appId: '1:271731699482:android:b5c9e62c606efd9aefc6a3',
    messagingSenderId: '271731699482',
    projectId: 'homeescape-75db4',
    storageBucket: 'homeescape-75db4.appspot.com',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCkgDVQk0GUQNC6Od_CNNx8Cj_M2xa9nCk',
    appId: '1:271731699482:web:89243603eed72616efc6a3',
    messagingSenderId: '271731699482',
    projectId: 'homeescape-75db4',
    authDomain: 'homeescape-75db4.firebaseapp.com',
    storageBucket: 'homeescape-75db4.appspot.com',
    measurementId: 'G-K61TRNCJFW',
  );
}
